import javax.mail.Address;
import java.util.*;

//Object setup for storage of individual emails - to store in arrays, databases, and the like

public class eMailObject {
    public List<Address> senders; //List of email senders
    public List<Address> recipients; //Receivers of the email
    public Date sentDate; //Date sent
    public Date receivedDate; //Date received/written into client?
    public String subject; //Email subject
    public int message_ID; //Unique identifier for email, generated by sender
    public List<String> tags; //Tags to apply to email - unique semantic identifier
    public HashMap<String, Double> tfidfMap; //For searching, instead of storing body
    public boolean hasMap; //Whether the email has already had a hashmap assigned, or not
    public int mailServer; //For identification of the email's associated mailserver/account
    public String firstLine; //Storage of first line of the email //TODO
    //Potential future additions to object - reference, tags, etc.

    public eMailObject(List<Address> senders, List<Address> recipients,
                       Date sentDate, Date receivedDate, String subject, int message_ID, int mailServer)
    {
        this.senders = senders;
        this.recipients = recipients;
        this.sentDate = sentDate;
        this.receivedDate = receivedDate;
        this.subject = subject;
        this.message_ID = message_ID;
        this.tags = new ArrayList<String>();
        this.tfidfMap = new HashMap<String, Double>();
        this.mailServer = mailServer;
    }

    public List<Address> getSenders() {
        return senders;
    }

    public void setSenders(List<Address> senders) {
        this.senders = senders;
    }

    public List<Address> getRecipients() {
        return recipients;
    }

    public void setRecipients(List<Address> recipients) {
        this.recipients = recipients;
    }

    public Date getSentDate() {
        return sentDate;
    }

    public void setSentDate(Date sentDate) { this.sentDate = sentDate; }

    public Date getReceivedDate() { return receivedDate; }

    public void setReceivedDate(Date receivedDate) { this.receivedDate = receivedDate; }

    public String getSubject() {
        return subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    public int getMessage_ID() { return message_ID; }

    public void setMessage_ID(int message_ID) { this.message_ID = message_ID; }

    public List<String> getTags() { return tags; }

    public void addTag(String tag) { this.tags.add(tag); }

    public HashMap getTfidfMap() { return tfidfMap; }

    public void addToMap(String term, Double value)
    {
        this.hasMap = true;

        if (tfidfMap.containsKey(term))
        {
            tfidfMap.put(term, tfidfMap.get(term) + value);
        }
        else
        {
            tfidfMap.put(term, value);
        }

    }

    public boolean hasMap() { return hasMap; }

    public int getMailServer() { return mailServer; }

    public void setMailServer(int mailServer) { this.mailServer = mailServer; }
}