import javax.mail.Address;
import java.util.Date;

//Object setup for storage of individual emails - to store in arrays, databases, and the like

public class eMailObject {
    private Address[] senders; //List of email senders
    private Address[] recipients; //Receivers of the email
    private Date sentDate; //Date sent
    private String subject; //Email subject
    private Object body; //Email body - not filled when created
    private int message_ID; //Unique identifier for email, generated by sender
    private String[] tags; //Tags to apply to email - unique semantic identifier
    //Potential future additions to object - reference, tags, etc.



    public eMailObject(Address[] senders, Address[] recipients, Date sentDate, String subject, Object body,
                       int message_ID, String[] tags) {
        this.senders = senders;
        this.recipients = recipients;
        this.sentDate = sentDate;
        this.subject = subject;
        this.body = body;
        this.message_ID = message_ID;
        this.tags = tags;
    }

    public Address[] getSenders() {
        return senders;
    }

    public void setSenders(Address[] senders) {
        this.senders = senders;
    }

    public Address[] getRecipients() {
        return recipients;
    }

    public void setRecipients(Address[] recipients) {
        this.recipients = recipients;
    }

    public Date getSentDate() {
        return sentDate;
    }

    public void setSentDate(Date sentDate) { this.sentDate = sentDate; }

    public String getSubject() {
        return subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    public String getBody() {
        return body.toString();
    }

    public void setBody(Object body) {
        this.body = body;
    }

    public int getMessage_ID() { return message_ID; }

    public void setMessage_ID(int message_ID) { this.message_ID = message_ID; }

    public String[] getTags() { return tags; }

    public void setTags(String[] tags) { this.tags = tags; }
}

